# Generated by Django 4.1.4 on 2022-12-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/doctor/')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialists')),
            ],
        ),
    ]
