# Generated by Django 4.1.3 on 2022-12-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctors')),
                ('specname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialists')),


            ],
        ),
    ]
